#ifndef FORWARDS_HPP
#define FORWARDS_HPP

// QT
class QLayout;
class QGridLayout;
class QHBoxLayout;
class QVBoxLayout;
class QGraphicsView;
class QGraphicsScene;
class QPushButton;
class QToolButton;
class QRadioButton;
class QWidget;
class QFrame;
class QLabel;
class QProgressBar;
class QSplitter;
class QStackedWidget;
class QListView;
class QListWidget;
class QTreeView;
class QTreeWidget;
class QTableView;
class QTableWidget;
class QAbstractItemModel;
class QStandardItemModel;
class QStringListModel;
class QStandardItem;
class QToolBox;
class QCheckBox;
class QComboBox;
class QToolButton;
class QString;
class QRubberBand;
class QGraphicsProxyWidget;
class QPropertyAnimation;
class QLineEdit;
class QPlainTextEdit;
class QLCDNumber;
class QGroupBox;

// CUSTOM
class CCentralViewLayout;
class CToolbarBorderLayout;
class CMainTitleBar;
class CDataDisplay;
class CImageDisplay;
class C3dDisplay;
class CDataViewer;
class CGLWidget;
class CImageScene;
class CImageView;
class CMainView;
class CPane;
class CStackedPane;
class CProjectPane;
class CProcessPane;
class CProtocolPane;
class CInfoPane;
class CResultsViewer;
class CDoubleView;
class CDataListView;
class CDataListViewDelegate;
class CProjectViewProxyModel;
class CProtocolView;
class CModuleDockWidget;
class CVolumeDisplay;
class CRollupWidget;

#endif // FORWARDS_HPP
