#ifndef LOGCATEGORY_H
#define LOGCATEGORY_H

//Register log category
Q_DECLARE_LOGGING_CATEGORY(logGraphics)
Q_DECLARE_LOGGING_CATEGORY(logPlugin)
Q_DECLARE_LOGGING_CATEGORY(logProcess)
Q_DECLARE_LOGGING_CATEGORY(logProgress)
Q_DECLARE_LOGGING_CATEGORY(logProject)
Q_DECLARE_LOGGING_CATEGORY(logProtocol)
Q_DECLARE_LOGGING_CATEGORY(logRender)
Q_DECLARE_LOGGING_CATEGORY(logResults)
Q_DECLARE_LOGGING_CATEGORY(logStore)
Q_DECLARE_LOGGING_CATEGORY(logUser);
Q_DECLARE_LOGGING_CATEGORY(logVideo)
Q_DECLARE_LOGGING_CATEGORY(logWizard)

#endif // LOGCATEGORY_H
